---

django_user: bpp
django_project_name: django_bpp
django_hostname: "{{ inventory_hostname }}"

django_settings_module: django_bpp.settings.production

database_user: "{{ django_user }}"
database_name: "{{ django_user }}"
database_host: "{{ postgresql_host }}"
database_password: "{{ lookup('password', 'credentials/' + inventory_hostname + '/' + database_user + '/' + '/database_password length=25') }}"

django_secret_key: "{{ lookup('password', 'credentials/' + inventory_hostname + '/' + django_user + '/' + django_project_name + '/' + '/django_secret_key length=512') }}"


django_group: "{{ django_user }}"

supervisor_logdir: /var/log/supervisor

django_home_dir: /home/{{ django_user }}
django_envfile: "{{ django_home_dir }}/.env"

django_media_root: /home/{{ django_user }}/media

django_venv_dir: "{{ django_home_dir }}/env"

django_python_version: "{{ python_version }}"
django_envvar_prefix: "{{ django_project_name|upper }}"

django_manage_py: "{{ django_home_dir }}/vexec python -mdjango_bpp.manage_command"

django_db_name: "{{ database_name }}"
django_db_user: "{{ database_user }}"
django_db_password: "{{ database_password }}"
django_db_host: "{{ database_host }}"
django_db_port: "{{ postgresql_port }}"

django_set_as_default_http_in_nginx: false
django_set_as_default_https_in_nginx: true

django_appserver_port: 9999

django_nginx_http_port: 80
django_nginx_https_port: 443

ssl_certs_path: "{{ role_path }}/files"

django_uzywaj_punktacji_wewnetrznej: 1

django_theme_name: app-blue

django_enable_new_reports: 1

django_session_security_warn_after: 540
django_session_security_expire_after: 600

django_password_duration_seconds: 2592000
django_password_use_history: 1
django_password_history_count: 12

django_bpp_punktuj_monografie: 1

django_bpp_inline_dla_autorow: stacked

supervisor_group_name: "{{ django_project_name }}_{{ django_hostname }}"
supervisor_no_processess: 3

django_bpp_redis_db_broker: 1
django_bpp_redis_db_celery: 2
django_bpp_redis_db_session: 4
django_bpp_redis_db_cache: 5
django_bpp_redis_db_locks: 6
