- name: "Zainstaluj konfigurację do {{ django_envfile }}"
  no_log: True
  ansible.builtin.template:
    src: envfile
    dest: "{{ django_envfile }}"
    mode: 0600
    owner: "{{ django_user }}"
    group: "{{ django_group }}"

- name: "activate script contains production environ setting"
  lineinfile:
    dest={{ django_venv_dir }}/bin/activate 
    line="export DJANGO_SETTINGS_MODULE=\"{{ django_settings_module }}\""

- name: make sure .bashrc exists
  command: touch {{ django_home_dir }}/.bashrc
  
- name: ".bashrc activates default environment"
  lineinfile: dest={{ django_home_dir }}/.bashrc line="{{ item }}"
  with_items:
    - "source {{ django_venv_dir }}/bin/activate"

- name: make sure .zshrc exists
  command: touch {{ django_home_dir }}/.zshrc
  
- name: ".zshrc activates default environment"
  lineinfile: dest={{ django_home_dir }}/.zshrc line="{{ item }}"
  with_items:
    - "source {{ django_venv_dir }}/bin/activate"

- name: ".pgpass created"
  no_log: True
  lineinfile:
    dest: "{{ django_home_dir }}/.pgpass"
    line: "{{ django_db_host }}:{{ django_db_port }}:{{ django_db_name }}:{{ django_db_user }}:{{ django_db_password }}"
    create: yes
    mode: 0600
