- include_vars:
    file: ../../postgresql-server/defaults/main.yml
    name: psql_defaults

- name: Update apt cache
  apt:  update_cache=yes

- name: Install apt packages and PostgreSQL version {{ postgresql_version|default(psql_defaults.postgresql_version) }}
  ansible.builtin.apt:
    pkg:
      - build-essential
      - python3-psycopg2
      - postgresql-common
      - postgresql-client-{{ postgresql_version|default(psql_defaults.postgresql_version) }}
      - libpq-dev
      - acl
      
      # Poniższe potrzebne jest, zeby generowanie PDFów przez WeasyPrint
      # ładnie chodziło. WeasyPrint wymaga paru bibliotek, które wczytuje
      # przez bodajże cdll, stąd, żeby się nie wysypywał. Rzecz jasna,
      # na ubuntu 20.04, bo w kolejnych wersjach może być różnie... 
      - pango1.0-tests

      # Poniższe potrzebne są, żeby można było zbudować python-ldap
      - libsasl2-dev
      - python3-dev
      - libldap2-dev
      - libssl-dev

      # Ech. 
      - emacs-nox

- include: postgresql.yml
  tags: ['database']

- name: Group for django site is present
  group: name={{ django_group }}

- name: User for django site is present
  user: name={{ django_user  }} createhome=yes shell=/bin/bash

- name: chmod 755 for user home dir, nginx static files needs it
  ansible.builtin.file:
    path: "{{ django_home_dir }}"
    mode: "0755"

- name: Media dir for django site is present
  file: path={{ django_media_root }} state=directory owner={{ django_user }} mode=0755

- name: Basic django requirements are installed
  ansible.builtin.apt:
    pkg:
      - python3-virtualenv
      - python{{django_python_version}}-dev
      - zip # jest wymagany
      - pandoc

- name: Virtualenv is created
  command: virtualenv --python=python{{ django_python_version }} {{ django_venv_dir }}
  become: yes
  become_user: "{{ django_user }}"
  args:
    creates: "{{ django_venv_dir }}"

- name: Virtualenv wrapper for execution of scripts is created
  template: src=vexec dest={{ django_home_dir }}/vexec mode=755
  become: yes  
  become_user: "{{ django_user }}"

- name: Pip is upgraded in virtualenv
  command: "{{ django_home_dir }}/vexec pip install --upgrade pip"
  become: yes
  become_user: "{{ django_user }}"
  tags: ['pip']

- include: config.yml
  tags: ['config']

- name: Instalacja pakietu BPP (to może chwilę potrwać...)
  command: "{{ django_home_dir }}/vexec pip install --upgrade --pre {{ django_package_name }}"
  # Ponizsze bylo uzywane przy instalacji z prywatnego repo
  # --extra-index-url http://dev.iplweb.pl:8080/ --trusted-host dev.iplweb.pl
  become: yes
  become_user: "{{ django_user }}"
  tags: ['django-depends', pip]
  environment:
    LANG: pl_PL.UTF-8
    LC_ALL: pl_PL.UTF-8

- name: Migracja bazy danych (przy pierwszym uruchomieniu to może dłuuuugo potrwać...)
  become: yes
  become_user: "{{ django_user }}"
  command: "{{ django_manage_py }} migrate --noinput"
  tags: ['django-migrate']

- name: Site name for sites framework is set up
  become: yes
  become_user: "{{ django_user }}"
  command: "{{ django_manage_py }} set_site_name --domain \"{{ django_hostname }}\" --name \"{{ django_site_name }}\""

- include: supervisor.yml
  tags: ['supervisor',]

- include: nginx.yml
  tags: ['nginx',]

- include: cron.yml
  tags: ['cron',]

- name: Check if any processess running
  shell: supervisorctl status {{ supervisor_group_name }}:* | grep RUNNING | wc -l
  register: supervisor_processess_running
  tags: ['supervisor',]

- name: Send HUP signal to running processess
  shell: supervisorctl signal HUP {{ supervisor_group_name }}:*
  when: supervisor_processess_running.stdout|int == supervisor_no_processess
  tags: ['supervisor',]

- name: Restart supervisor if different number of running procs
  shell: ls
  notify: supervisor restart all
  when: supervisor_processess_running.stdout|int != supervisor_no_processess
  tags: ['supervisor',]

- name: Check if the installed site can send mails
  command: "{{ django_manage_py }} sendtestemail --admin"
  ignore_errors: yes
  tags: ['sendtestemail']
  become: yes
  become_user: "{{ django_user }}"

