---
- name: Add deadsnakes PPA
  ansible.builtin.apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    state: present
    
- name: Update apt cache
  apt:  update_cache=yes

- name: Install package
  apt: name="python{{ python_version }}" state="present"
