- name: Add PostgreSQL repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ubuntu_codename }}-pgdg main
    update_cache: no

- name: Add PostgreSQL repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Update apt cache
  apt:  update_cache=yes

- name: Install apt packages and PostgreSQL version {{ postgresql_version }}
  apt: name={{ item }} state=present
  with_items: 
    - postgresql-{{ postgresql_version }}
    - postgresql-plpython3-{{ postgresql_version }}
    - postgresql-contrib-{{ postgresql_version }}

    # na potrzeby Ansible
    - python-psycopg2
    - python3-psycopg2

    # dla zbudowania pozniej psycopg2
    - build-essential
    - libpq-dev

- name: Start service, if not started
  service:
    name: postgresql
    state: started
    
- name: Create PostgreSQL user
  postgresql_user: name={{ database_user }} password={{ database_password }} role_attr_flags=CREATEDB,SUPERUSER state=present port={{ postgresql_port }}
  become_user: postgres

- name: CreatePostgreSQL database  
  postgresql_db: name={{ database_name }} port={{ postgresql_port }}
  args: 
    owner: "{{ database_user }}"
    state: present 
    encoding: UTF-8
    lc_collate: pl_PL.UTF-8
    lc_ctype: pl_PL.UTF-8
    template: template0
  become_user: postgres
  
- name: Create PostgreSQL plpython language
  postgresql_lang: db={{ database_name }} lang=plpython3u state=present port={{ postgresql_port }}
  become_user: postgres

- name: Create PostgreSQL collation for pl_PL
  shell: psql -c "CREATE COLLATION pl_PL(locale='pl_PL.utf8');" "{{ database_name }}"
  become_user: postgres
  ignore_errors: yes
  register: psql_coll_err

- name: Check for unexpected error message (if any)
  fail: msg="Nieoczekiwany błąd podczas tworzenia collation"
  when: (psql_coll_err.stderr != "" and (psql_coll_err.stderr.find("już istnieje") < 0 and psql_coll_err.stderr.find("already exists") < 0))

- name: Create PostgreSQL collation for pl_PL
  shell: psql -c "CREATE COLLATION \"pl_PL.utf8\"(locale='pl_PL.utf8');" "{{ database_name }}"
  become_user: postgres
  ignore_errors: yes
  register: psql_coll_err_2

- name: Check for unexpected error message (if any)
  fail: msg="Nieoczekiwany błąd podczas tworzenia collation"
  when: (psql_coll_err_2.stderr != "" and (psql_coll_err_2.stderr.find("już istnieje") < 0 and psql_coll_err_2.stderr.find("already exists") < 0))

- name: Update unaccent.txt file
  file: src=unaccent-rules.txt dest=/usr/share/postgresql/{{ postgresql_version }}/tsearch_data/unaccent.rules
