- name: Update apt cache
  apt:  update_cache=yes

- name: Install apt packages and PostgreSQL version {{ postgresql_version }}
  ansible.builtin.apt:
    pkg:
      - postgresql-{{ postgresql_version }}
      - postgresql-plpython3-{{ postgresql_version }}
      - postgresql-contrib-{{ postgresql_version }}
      - python3-psycopg2 # dla Ansible, bez tego zarządzanie nie pójdzie.

- name: Start service, if not started
  service:
    name: postgresql
    state: started

- name: hold until Postgresql is up and running
  wait_for:
    host: 127.0.0.1
    port: 5432

- name: Set password for PostgreSQL user
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user:
    db: template1
    name: postgres
    password: "{{ postgresql_password }}"

- name: Update unaccent.txt file
  copy: src=unaccent-rules.txt dest=/usr/share/postgresql/{{ postgresql_version }}/tsearch_data/unaccent.rules
