---
- hosts:
    - bpp-dbserver
  become: yes
  become_method: sudo
  roles:
    - locale
    - postgresql-server
    # - TODO: remote access cfg
    # - TODO: pgtune

- hosts:
    - bpp-webserver
  become: yes
  become_method: sudo
  roles:
    - swapfile
    - locale
    - nginx
    - redis-server
    - python
    - name: bpp-site
      tags: ['bpp-site',]
