---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - locale
    - postgresql-server
    - nginx
    - rabbitmq-server
    - redis-server
    - python
    - bpp-site

  tasks: 
    - name: RabbitMQ config jest dodany do {{ django_venv_dir }}/bin/activate
      no_log: True
      lineinfile: dest="{{ django_venv_dir }}/bin/activate" line="{{ item }}"
      with_items:
        - export {{ django_envvar_prefix }}_BROKER_URL="amqp://{{ rabbitmq_user }}:{{ rabbitmq_password }}@localhost:5672/{{ rabbitmq_vhost }}"
      notify:
        - supervisor restart
      tags: ['django-site', 'rabbitmq', 'config']

