---
postgresql_port: 5432
postgresql_version: 14

postgresql_user: postgres
postgresql_password: "{{ lookup('password', 'credentials/' + postgresql_host + '/postgresql_system_password length=50') }}"
