---
postgresql_port: 5432
postgresql_version: 14

postgresql_user: postgres
postgresql_host: localhost
postgresql_password: "{{ lookup('password', 'credentials/' + inventory_hostname + '/' + postgresql_host + '/postgresql_system_password length=50') }}"
