name: Test build on Vagrant

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Show Vagrant version
      run: vagrant --version

    - name: Install vagrant-hostmanager plugin
      run: vagrant plugin install vagrant-hostmanager
      
    - name: Run vagrant up
      run: vagrant up

    - name: Install Ansible
      run: pip install ansible

    - name: ssh into box after boot
      run: vagrant ssh -c "echo 'hello world!'"
      
    - name: debug3
      run: find ~/.ssh
      
    - name: debug2
      run: find .vagrant

    - name: debug5
      run: cat /etc/hosts
      
    - name: Ansible it
      run: make staging-ansible
